"""
research/strategies/ml_rules.py — Strategy 6: ML-Extracted Rules
Auto-generated by research/ml_rule_extractor.py.
Contains explicit if/then rules derived from trained decision tree paths.
Do not edit manually — re-run ml_rule_extractor.py to regenerate.
"""
